"""10.0 coding: converters are exact (cURL, JSON types, regex, bases of
.gitignore), files run in their language, lessons check themselves, and the
Coding page edits, highlights and runs."""

from __future__ import annotations

import json
import sys

import pytest


@pytest.fixture
def jarvis(base):
    from jarvis.assistant import Jarvis

    return Jarvis(voice_enabled=False)


def test_curl_to_python_compiles_and_keeps_everything():
    from jarvis.ten import coding

    code = coding.curl_to_python("curl -X POST 'https://api.example.com/items?x=1' -H 'Content-Type: application/json' "
                                 "-H 'Authorization: Bearer abc' -d '{\"name\": \"pen\", \"ok\": true}'")
    compile(code, "<curl>", "exec")
    assert "requests.post('https://api.example.com/items?x=1'" in code
    assert "json=payload" in code and "'ok': True" in code.replace('"', "'") and "Bearer abc" in code
    code = coding.curl_to_python("curl https://x.io -u ali:secret -k")
    assert "auth=('ali', 'secret')" in code and "verify=False" in code and "requests.get" in code


def test_json_to_types():
    from jarvis.ten import coding

    data = {"id": 1, "name": "Ada", "price": 9.5, "tags": ["a"], "owner": {"login": "x", "admin": False},
            "items": [{"sku": "a1", "qty": 2}, {"sku": "b2", "qty": 1, "note": None}]}
    py = coding.json_to_types(data, "python")
    namespace: dict = {}
    exec(compile(py, "<types>", "exec"), namespace)  # noqa: S102 — code generated by the test itself
    assert "class Owner" in py and "items: list[Item]" in py and "tags: list[str]" in py
    ts = coding.json_to_types(data, "typescript")
    assert "export interface Root" in ts and "owner: Owner;" in ts and "price: number;" in ts
    go = coding.json_to_types(data, "go")
    assert 'json:"owner"' in go


def test_regex_gitignore_url_and_markdown(jarvis):
    from jarvis.ten import coding

    r = coding.regex_test(r"(\d{3})-(\d{4})", "call 555-1234 or 555-9876")
    assert r["count"] == 2 and r["matches"][0]["groups"] == ("555", "1234")
    assert "node_modules/" in coding.gitignore(["js", "vscode"])
    with pytest.raises(coding.CodingError):
        coding.gitignore(["cobol"])
    assert jarvis.process("/url encode a b&c").text == "a%20b%26c"
    assert "q = hello world" in jarvis.process("/url parse https://x.com/s?q=hello+world").text
    html = coding.markdown_to_html("# Title\n- one\n- two\n\n```\ncode <b>\n```\n**bold**")
    assert "<h1>Title</h1>" in html and "<li>one</li>" in html and "&lt;b&gt;" in html and "<strong>bold</strong>" in html


def test_project_stats_and_runcode(jarvis, tmp_path):
    (tmp_path / "a.py").write_text("# comment\nimport os\n\nprint('hi from a')\n", encoding="utf-8")
    (tmp_path / "b.js").write_text("// c\nconsole.log(1)\n", encoding="utf-8")
    out = jarvis.process(f"/projectstats {tmp_path}").text
    assert "Python" in out and "JavaScript" in out
    from jarvis import security

    security.permissions.set_asker(lambda request: True)
    out = jarvis.process(f"/runcode {tmp_path / 'a.py'}").text
    assert "exit 0" in out and "hi from a" in out


def test_lessons_check_themselves():
    from jarvis.ten import coding

    lesson = next(l for l in coding.LESSONS if l["id"] == "functions")
    ok, _ = coding.check_lesson(lesson, "def square(n):\n    return n * n\n", python=sys.executable)
    assert ok
    ok, message = coding.check_lesson(lesson, "def square(n):\n    return n + n\n", python=sys.executable)
    assert not ok and "AssertionError" in message
    first = coding.LESSONS[0]
    assert coding.check_lesson(first, "print('Hello, JARVIS')", python=sys.executable)[0]


def test_pydoc_and_shortcuts(jarvis):
    assert "split" in jarvis.process("/pydoc str.split").text
    assert "Command palette" in jarvis.process("/ideshortcuts vscode").text


from tests.test_gui import _display_available, app  # noqa: E402,F401


@pytest.mark.skipif(not _display_available(), reason="no display")
def test_the_coding_page_opens_edits_and_highlights(app, tmp_path):
    (tmp_path / "main.py").write_text("def hello():\n    return 'hi'  # greet\n", encoding="utf-8")
    app._show_tab("code")
    app.update()
    page = app.pages["code"]
    page.open_folder(str(tmp_path))
    page.open_file(tmp_path / "main.py")
    editor = page.current
    assert editor is not None and editor.text.tag_ranges("Keyword") and editor.text.tag_ranges("Comment")
    editor.text.insert("end", "\nprint(hello())\n")
    app.update()
    assert editor.dirty
    page.save_current()
    assert "print(hello())" in (tmp_path / "main.py").read_text(encoding="utf-8")
    assert not editor.dirty
    editor.text.tag_add("sel", "1.0", "2.end")
    editor._comment()
    assert editor.content().startswith("# def hello")
    page.open_lesson(page.app.jarvis and __import__("jarvis.ten.coding", fromlist=["x"]).LESSONS[0])
    assert page.check_btn.winfo_manager()
